[package]
name = "tensorboard-peek"
version = "0.1.0"
authors = ["Ryan Huang <NPN@users.noreply.github.com>"]
edition = "2018"

[dependencies]
crossterm = "0.18"
tfrecord = { version = "0.7", features = ["summary"] }
tui = { version = "0.14", default-features = false, features = ["crossterm"] }
